### ISSUE TITLE
Permission denied err on eri_nogpu_dev

### ISSUE THREAD

**Issue by oersoy1** [ElderResearch/gpu_docker#11]
Can’t seem to create any files in Jupyter — “Permission denied: Untitled.ipynb” (`eri_nogpu_dev:latest`)

For the same user `tshafer` other docker images work fine.

**Comment by RZachLamberty** [comment]
the `eri_nogpu_dev` image on the box had not been updated, so this was defaulting to the previous iteration (where users were all put into `/userhome`, not `/home/$USER`). because I was no longer mounting the server home directory to the docker `/userhome` directory, the image picked up the previously-created docker volume for `/userhome`. this had root-level permissions, hence the permission error.

this was fixed not with a code update but rather by actually building the image we claimed was current for `eri_nogpu_dev:latest`

**Comment by RZachLamberty** [comment]
disciplined approach to fixing this, going forward: maybe only reference tagged versions in code (with a global variable the user can increment to recognize version updates, e.g.). this runs the risk of possibly also causing problems, where we update containers but forget to update the script that launches them.

something to think about.
